### ISSUE TITLE
Bundle version 7 todo list (Symfony 7 support)

### ISSUE THREAD

**Issue by scheb** [scheb/2fa#209]
This issue is to keep track of my todo list for the upcoming bundle version 7 (Symfony 7 support) :)

- [x] Remove deprecated properties/methods
- [x] Upgrade codebase to PHP 8.2 style where possible
- [x] Upgrade code examples in the docs with PHP 8.2 code style
- [x] Upgrade notes
- [x] Clean up code that is no longer needed and remove compatibility layers
- [x] Update CONTRIBUTING.md on language features to be used
- [x] Update "Brute Force" approach in the docs
- [x] Update .symfony.bundle.yaml
- [x] Update version number and compatible Symfony versions in 7.x docs
- [x] Drop old versions of dependencies
- [x] Remove error when the old security system is used (no longer possible)
- [x] Update mentions of "6.x" to "7.x" on the 7.x branch (i.e. docs and issue templates and gitsplit workflow)
- [x] Update version guidance on 7.x branch
- [x] Clean up the `app`
- [x] Upgrade code style
- [x] Check for skipped tests, whether these are still needed
- [x] Working integration tests
- [x] Create alternative for the flawed `window` config option
- [x] Update gitsplit config

Pre-Release Cleanup (once Symfony 7 stable is released)

- [x] Remove `minimum-stability` from composer.json files
- [x] Remove `@dev` from composer.json files
- [x] Rewrite commits to clean up fiddling with CI and dependencies

Release

- [x] Change default branch on Github to 7.x
- [x] Release 🥳 
- [x] Abandon version 5.x, update version guidance
- [x] Update version guidance on 6.x branch

Post-Release

- [x] Remove `.symfony.bundle.yaml` from 6.x
- [x] Change default branch of sub-packages to 7.x

**Comment by Chris53897** [comment]
Thanks for your work.

Symfony 7 is released today
https://symfony.com/blog/symfony-7-0-0-released
