### ISSUE TITLE
Bundle version 6 todo list

### ISSUE THREAD

**Issue by scheb** [scheb/2fa#81]
This issue is to keep track of my todo list for the upcoming bundle version 6 :)

Reference: #62

- [x] Remove deprecated properties/methods
- [x] Abandon scheb/two-factor-bundle
- [x] Upgrade codebase to PHP 8.0 style, i.e. property types
- [x] Upgrade code examples in the docs with PHP 8.0 code style
- [x] Upgrade notes, mention switch to authenticator security
- [x] Remove getProviderKey, replace with getFirewallName
- [x] Clean up code that is no longer needed and remove compatibility layers
- [x] Update CONTRIBUTING.md on language features to be used
- [x] Update "Bypassing Two-Factor Authentication" approach in the docs
- [x] Remove scheb/2fa-qr-code package (code & gitsplit)
- [x] Update docs with a code example how to render QR code
- [x] PHPUnit: Fix "Element 'coverage': This element is not expected."
- [x] Remove dependency and docs on `symfony/swiftmailer-bundle`
- [x] Update .symfony.bundle.yaml
- [x] Update version number and compatible Symfony versions in 6.x docs
- [x] Drop old versions of lcobucci/jwt and spomky-labs/otphp
- [x] Bump min version of paragonie/constant_time_encoding to 2.4
- [x] Make sure the bundle errors when used on Symfony 5.4 with old security system
- [x] Add passport to the authentication context
- [x] Upgrade notes for interface signature changes
- [x] Update mentiones of "5.x" to "6.x" on the 6.x branch (i.e. docs and issue templates and gitsplit workflow)
- [x] Update version guidance on 5.x and 6.x branches
- [x] Migrate away from `AuthenticationHandlerInterface` and use `TwoFactorConditionInterface` instead
- [x] Constructor readability
- [x] Clean up the `app`
- [x] Upgrade code style
- [x] MockObject return union types
- [x] Migrate to PHP configs

Release

- [x] Update version guidance on 5.x branch
- [x] Change default branch on Github and on Scrutinizer
- [x] Release 🥳 
- [x] Update Flex recipe (remove old security token `PostAuthenticationGuardToken`)
- [x] Remove `.symfony.bundle.yaml` from 5.x
